### ISSUE TITLE
MESE NEXT engine 

### ISSUE THREAD

**Issue by looooown2006** [hczhcz/mese-next#2]
Hi there,
I'm a high school student.
I hope this message finds you well. I am reaching out to you because I am interested in using the "mese next Engine" that you have developed on my upcoming project. From my research, it seems like your engine is the perfect fit for what I am trying to achieve.I am going to showcase the mese system in a class presentation and I would really appreciate your help in obtaining the engine so that I can use it in my project. If it is possible, could you please share the necessary files or instructions for me to get started? 
Thank you so much for your time and consideration. I look forward to hearing back from you soon.

**Comment by hczhcz** [comment]
It is here: https://github.com/hczhcz/mese-next/commit/180b06f41e94976bd34c273ac5ad9df02ba5576f
You will need a Linux environment (installed on your computer, virtual machine, or VPS) to run it.

**Comment by looooown2006** [comment]
> It is here: [180b06f](https://github.com/hczhcz/mese-next/commit/180b06f41e94976bd34c273ac5ad9df02ba5576f) You will need a Linux environment (installed on your computer, virtual machine, or VPS) to run it.

Thank you very much for your reply！ I have another question:Do I need to set up a server to connect a mongodb to the server,and then i can login the website in the zip?

**Comment by hczhcz** [comment]
> Do I need to set up a server to connect a mongodb to the server,and then i can login the website in the zip?

Yes. Setup instructions are available in `readme.md`.
