### ISSUE TITLE
needs a guideline how to run server 

### ISSUE THREAD

**Issue by qwani** [hczhcz/mese-next#3]
great work  but needs a more detailed step by step guideline to run server and edit configs and running client side in browser 
as i used al reasonable paths but no access to run game

**Comment by CodingDiego** [comment]
I would love a step by step either video or guide with orientating
pictures, cause last time I tried to run it i got lost

**Comment by hczhcz** [comment]
This project is not maintained for some years.
It is recommended to use the [telegram version](https://github.com/hczhcz/mese-next-telegram) or use [mese_bot](https://t.me/mese_bot) directly.
